spring.application.name=cinema

# Configuration du serveur
server.port=8080

# Configuration JSP (InternalResourceViewResolver)
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.thymeleaf.enabled=false

spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false
spring.mvc.view.cache=false
server.servlet.jsp.init-parameters.development=true